### ISSUE TITLE
Перемещение классов в папку lib

### ISSUE THREAD

**Issue by AgelxNash** [Pathologic/SimpleGallery#37]
Классы типа FileAPI и fileHelper вполне самодостаточны и могут быть использованы вне плагина simplegallery. В связи с этим вопрос - может быть есть смысл переместить их в папку assets/lib(s), чтобы их можно было использовать и в других компонентах без дополнительных проверок в стиле class_exists и не плодить однотипные классы, как это сейчас принято с phx

**Comment by Pathologic** [comment]
Класс для встраивания вкладки
Класс для загрузки js
Класс для генерации превьюшек в админке

**Comment by Pathologic** [comment]
@AgelxNash что-то все равно получается ерунда. Положу я эти классы в lib, а потом что - отдельный репозиторий для классов и "поставьте то, поставьте это и еще вот это тоже"? А в одну кучу все смешивать как в DocLister тоже не хочется. Может надо переходить на composer, заодно и с автозагрузкой ведь должен вопрос решиться?

**Comment by AgelxNash** [comment]
@Pathologic я изначально имел в виду перенос этих классов в репозиторий DocLister'a, т.к. зачастую новые решения строятся на базе него.

Что касается composer'a, то в свое время я начинал разработку модуля [MODXComposer](https://github.com/AgelxNash/MODXComposer), который работает на базе компонента [composer/installers](https://github.com/composer/installers/blob/master/src/Composer/Installers/MODXEvoInstaller.php), но так и не довел это решение до ума, т.к. работать этот модуль будет не на всех хостингах.

Смотри сам. Пусть остается пока так, а там либо MODX Evo сдохнет или у меня появится время на доработку.

**Comment by Pathologic** [comment]
В DocLister тоже не вариант - уже сейчас его быстрее ставить руками, чем чекбоксы отмечать в репозитории. (:
