### ISSUE TITLE
ManagerManager + MultiTV + SimpleGallery

### ISSUE THREAD

**Issue by AgelxNash** [Pathologic/SimpleGallery#57]
SimpleGallery загружает easyUI версии 1.4.1. На сколько я знаю, для SimpleGallery можно определить свои скрипты, но как я понял - они догружаются в довесок к существующим. Т.е. нельзя вот так жестко взять и выкинуть какой-то скрипт или подменить его

MultiTV по умолчанию тянет за собой jQuery UI 1.10.4. При чем зашито это [жестко в конфиге](https://github.com/Jako/multiTV/blob/master/assets/tvs/multitv/settings/default.setting.inc.php#L18), который загружается одним из последних. Т.е. обойти нет возможности.

ManagerManager для некоторых виджетов тоже по умолчанию тянет jQuery UI версии 1.10.3. Но тут, к счастью, это обходится легко созданием копии виджета и удалением от туда строки загрузки jQuery UI. Все ничего, но есть один виджет - [mm_ddSelectDocuments](https://github.com/DivanDesign/MODXEvo.plugin.ManagerManager.mm_ddSelectDocuments), который никак не хочет работать если включается SimpleGallery. Даже если убрать из этого виджета загрузку jQuery UI.

**Comment by Ronef** [comment]
mm_ddSelectDocuments 100% не будет работать без jQuery UI.

**Comment by AgelxNash** [comment]
Опытным путем удалось установить, что конфликтым является файл jquery.ddMultipleInput-1.2.1.min.js от виджета ManagerManager. К SimpleGallery этот багрепорт не имеет ни какого отношения.

**Comment by Pathologic** [comment]
@AgelxNash теперь можно подменить scripts.json: https://github.com/Pathologic/SimpleGallery/commit/a7955775e6481aa38e7704b0f758bd44ea527904

**Comment by AgelxNash** [comment]
@Pathologic еще бы jsList подхватывался из параметра к плагину и мог размещаться в произвольной папке, а не только в папке плагина SimpleGallery;-)

**Comment by Ronef** [comment]
@AgelxNash «Опытным путем удалось установить» — это консолька ругается на что-то там в этом файле?) Если же есть более подробная информация, я был бы рад её услышать.
