### ISSUE TITLE
Добавление фотоальбома к конкретной странице

### ISSUE THREAD

**Issue by AgelxNash** [Pathologic/SimpleGallery#67]
Собственно сабж. Помимо привязки по шаблону, хотелось бы еще иметь возможность создавать связку и с конкретным документом

**Comment by AgelxNash** [comment]
Чтобы активировать новый функционал, нужно в строку конфигурации плагина добавить
```
&documents=Documents;text; &ignoreDoc=Ignore Documents;text;
```

**Comment by Pathologic** [comment]
Привязка к документу поломает перемещение картинок в другие документы, там ведь по шаблонам проверяется.

**Comment by AgelxNash** [comment]
Проверил на своем проекте - все корректно перемещается.
