### ISSUE TITLE
Modx 1.1-d8.1.3 

### ISSUE THREAD

**Issue by bagi091** [Pathologic/SimpleGallery#78]
после [этого](https://github.com/dmi3yy/modx.evo.custom/commit/e2ec831a145ecea95fdb205a526b32fc12d7656e) коммита в modx используется jQuery 3.1, а из-за этого плагин SimpleGallery не может отобразиться, но если подключить jQuery migrate то все равно некорректно работает
1. нет прогресс бара при загрузке
2. не сворачивается диалоговое окно после загрузки
3. не генерируется превью в админке (пока не понял почему, возможно мой косяк)

**Comment by bagi091** [comment]
up.
3. Развернул пустой modx на другом хостинге, тоже самое, превью не создается

**Comment by bagi091** [comment]
up
3. Однажды мы на эту тему с вами разговаривали, дело в том, что после обновления MODx даже пустая строка передается в параметры плагина и соответственно неверно проходит проверку на isset().

Чтобы превью начало формироваться нужно заменить **isset** на **!empty** в [этой](https://github.com/Pathologic/SimpleGallery/blob/master/assets/plugins/simplegallery/lib/controller.class.php#L176) строке

**Comment by Pathologic** [comment]
Параметры, как я понял, так и не починили, вот и получается абы что. С jQuery я точно ничего не могу сказать, потому что даже на фронте ни разу не использовал 3ю версию. В теории проблемы могут вылезти не только в моем говнокоде, но и в компонентах, что еще хуже, потому что код того же EasyUI закрыт.
Если есть возможность, то попробуйте вернуть тот jQuery, который был в прошлых версиях.

**Comment by bagi091** [comment]
Не говнокод вовсe) 
пойду к Дмитрию
