### ISSUE TITLE
Documentation available?

### ISSUE THREAD

**Issue by fourroses666** [Pathologic/SimpleGallery#82]
I'd like to check this gallery plugin, where do I have to look for documentation? 
Even if its only in Russian language I might be able to translate it by Google translate.

**Comment by Pathologic** [comment]
Basic documentation is available at http://docs.evolution-cms.com/Extras/Plugins/SimpleGallery
But there are some problems in new Evo, because of jQuery 3.0, so it would be better to use  http://modx.com.ua/download/1.1rc-d7.1.6.html for tests.
