### ISSUE TITLE
бажит скрипт загрузки галереи в таб

### ISSUE THREAD

**Issue by gadev** [Pathologic/SimpleGallery#85]
http://modx.im/blog/dmi3yy/5265.html#comment45368

**Comment by Pathologic** [comment]
И как воспроизвести?

**Comment by gadev** [comment]
modx 9.1.7
открываете таб SimpleGallery, переходите на любую другу страницу, возвращаетесь на ту, где есть таб галереи. как результат, таб выбран, галерея не загружена. повторный клик на таб галерею загружает. т.е. при сохранении истории активной вкладки не отрабатывает js [https://github.com/Pathologic/SimpleGallery/blob/master/assets/plugins/simplegallery/tpl/simplegallery.tpl#L32](url)

**Comment by gadev** [comment]
можно и проще. открываем таб SimpleGallery, жмем cmd-shift-r - получаем пустой таб. актуально для любого браузера

**Comment by Pathologic** [comment]
Не получается. cmd-shift-r - это ctrl-shift-r? Тоже не получается.

**Comment by gadev** [comment]
вероятно, стояла не самая последняя версия sg. допускаю, что на текущей версии все ок, но проверить не выходит по причине отсутствия в пакете либы euiuploader, гугл о ней тоже ничего не знает :( ткните, где скачать, чтобы проверить

**Comment by Pathologic** [comment]
https://github.com/AgelxNash/DocLister

**Comment by gadev** [comment]
там ее нет. судя по [этому](https://github.com/Pathologic/SimpleGallery/blob/master/assets/plugins/simplegallery/js/scripts.json#L37), она должна быть [тут](https://github.com/AgelxNash/DocLister/tree/master/assets/js)

**Comment by Pathologic** [comment]
Исправил.

**Comment by gadev** [comment]
обновил dl и sg – теперь 500 ошибка. PHP Fatal error:  Call to undefined method SimpleGallery\sgData::setParams() in assets/plugins/simplegallery/lib/controller.class.php on line 23

**Comment by Pathologic** [comment]
Поправил и это.

**Comment by gadev** [comment]
видимо еще нужно обновить handlebars..
Error: Missing helper: 'stripText'  /assets/js/handlebars/handlebars.runtime.min.js:27
Error: Missing helper: 'bytesToSize'  /assets/js/handlebars/handlebars.runtime.min.js:27

**Comment by Pathologic** [comment]
https://github.com/AgelxNash/DocLister/commit/1c8b6ad03cc7a2bc350ef50fac46517469faa778

**Comment by gadev** [comment]
теперь все отлично. спасибо!
