### ISSUE TITLE
Lang de

### ISSUE THREAD

**Issue by leonie12** [Pathologic/SimpleGallery#90]
I have no idea how to contribute translations otherwise:

plugins/simplegallery/js/lang/de.js:`

_sgLang = [];
_sgLang['cancel'] = 'Abbrechen';
_sgLang['from'] = 'von';
_sgLang['close'] = 'Schließen';
_sgLang['file'] = 'Datei';
_sgLang['size'] = 'Größe';
_sgLang['delete'] = 'Löschen';
_sgLang['are_you_sure_to_delete'] = 'Das Bild wirklich löschen?';
_sgLang['error'] = 'Fehler';
_sgLang['delete_fail'] = 'Fehler beim Löschen.';
_sgLang['are_you_sure_to_delete_many'] = 'Ausgewählte Bilder wirklich löschen?';
_sgLang['createdon'] = 'Erstellt am';
_sgLang['title'] = 'Titel';
_sgLang['description'] = 'Beschreibung';
_sgLang['add'] = 'Additional';
_sgLang['show'] = 'Zeigen';
_sgLang['yes'] = 'Ja';
_sgLang['save'] = 'Speichern';
_sgLang['save_fail'] = 'Fehler beim Speichern.';
_sgLang['refresh_previews'] = 'Vorschauen erneuern';
_sgLang['are_you_sure_to_refresh'] = 'Dies kann lange dauern. Wirklich fortfahren?';
_sgLang['emptydesc'] = 'Bild-Beschreibung ist leer. Zum Bearbeiten anklicken.';
_sgLang['continue'] = 'Fortfahren';
_sgLang['refresh_current'] = 'Aktuelle Galerie erneuern';
_sgLang['refresh_ids'] = 'Erneuern anhand der ID';
_sgLang['refresh_tpls'] = 'Erneuern anhand des Templates';
_sgLang['refresh_fail'] = 'Fehler bei Erneuern der Vorschauen.';
_sgLang['move'] = 'Verschieben';
_sgLang['are_you_sure_to_move'] = 'Ausgewählte Bilder wirklich verschieben?';
_sgLang['move_fail'] = 'Fehler beim Verschieben.';
_sgLang['select_resource_id'] = 'ID des Dokuments auswählen:';
_sgLang['save_document_to_continue'] = 'Dokument speichern, um mit der Galerie zu arbeiten.';
_sgLang['server_error'] = 'Server-Fehler: ';
_sgLang['parse_error'] = 'Fehler bei der Verarbeitung';

`

**Comment by Pathologic** [comment]
added
