### ISSUE TITLE
Display type similar Maxigallery pictureview possible?

### ISSUE THREAD

**Issue by leonie12** [Pathologic/SimpleGallery#92]
Until now I used MaxiGallery with display type 'pictureview'. I.e. the gallery overview thumbnails do not open the image in a JS-lightbox but the normal size of pic (for example width 800 px) is displayed with picture title and description text and prev/next-Links on its own page. This normal pic is linking to the big/original sized image (for example 200px width).

Is this also possible with SG? What I found until now is that with SG the thumbnails open the bic pics directly as pic source [+sg_image+]. How can I output it like described above? Maybe I am not seeing the obvious?

**Comment by Pathologic** [comment]
You can use thumbSnippet and thumbOptions parameters:
```
&thumbSnippet=`phpthumb`
&thumbOptions = `w=400&h=400&zc=1`
```
or 
```
&thumbSnippet=`phpthumb`
&thumbOptions = `{
    "default":"w=400&h=400&zc=1",
    "small":"w=50&h=50&zc=1",
    "medium":"w=200&h=200&zc=1"
}`
```
Then placeholders are available for the first case:
```
[+thumb.sg_image+]
```
and for the second one:
```
[+thumb.sg_image+]
[+thumb_small.sg_image+]
[+thumb_medium.sg_image+]
```
It's the same if you write in chunk:
```
[[phpthumb? &input=`[+sg_image+]` &options=`w=400&h=400&zc=1`]]
[[phpthumb? &input=`[+sg_image+]` &options=`w=50&h=50&zc=1`]]
[[phpthumb? &input=`[+sg_image+]` &options=`w=200&h=200&zc=1`]]
```

It's simple way, but not effective. It's better create thumbnails during upload and as a result we'll get faster output and ability to delete thumbnails with their parent image - that's possible with plugins. sgThumb is the example of such plugin shipped by default. You can try to use it: enable  OnSimpleGalleryDelete, OnSimpleGalleryRefresh and OnFileBrowserUpload events, then fill Thumbnails configuration setting, for example:
```
[
{"template":3,"options":"w=320&h=200&zc=1","folder":"thumb"},
{"template":6,"options":"w=384&h=384&far=C&bg=000000","folder":"384x384"},
{"rid":9,"options":"w=500&h=500&zc=C&bg=000000","folder":"500x500"},
{"template":6,"options":"w=500&h=500&zc=C&bg=000000","folder":"500x500"}
]
```
To create thumbnails for existing images use Refresh previews button. Then use sgThumb snippet to output (folder name from thumbnail configuration is the value of options parameter for sgThumb snippet):
```
&thumbSnippet=`sgThumb`
&thumbOptions = `{
    "default":"500x500",
    "foobar":"384x384"
}`
```

**Comment by leonie12** [comment]
Thank you for this explanation. What I do not yet understand is how I get these medium sized pics output on its own page with its own URL (with GET parameters)  so that I have a gallery overview page with thumbnails (this I have working) and a page per pic with picture title, picture description text AND pagination/prev-/next-links?
This last part is what I do not understand how to output it. At the moment the thumbnails link to the big pic directly but I want to output it/the medium pic on its own HTML page with navigation header, footer like the rest of the website.

It would be very nice if you could give me a hint in the right direction.

**Comment by Pathologic** [comment]
You need to create a snippet, something like this:
```
<?php
if (isset($_GET['sgid']) && is_numeric($_GET['sgid'])) {
	$id = (int)$_GET['sgid'];
	$params['idType'] = 'documents';
	$params['documents'] = $id;
	$params['saveDLObject'] = '_IV';
	$out = $modx->runSnippet('sgLister', $params);
	$obj = $modx->getPlaceholder('_IV')->docsCollection();
	if ($obj->count()) {
		$nextTpl = isset($nextTpl) ? $nextTpl : '';
		$prevTpl = isset($prevTpl) ? $prevTpl : '';
		$rid = $obj->get($id)['sg_rid'];
		$DLTemplate = DLTemplate::getInstance($modx);
		$table = $modx->getFullTableName('sg_images');
		$q = $modx->db->query("SELECT `sg_id` FROM {$table} WHERE `sg_rid` = {$rid} AND `sg_id`<{$id} ORDER BY `sg_id` DESC LIMIT 1");
		if ($prev = $modx->db->getValue($q)) {
			$modx->setPlaceholder('prev', $DLTemplate->parseChunk($prevTpl, array('prev' => $prev)));
		}
		$q = $modx->db->query("SELECT `sg_id` FROM {$table} WHERE `sg_rid` = {$rid} AND `sg_id`>{$id} ORDER BY `sg_id` ASC LIMIT 1");
		if ($next = $modx->db->getValue($q)) {
			$modx->setPlaceholder('next', $DLTemplate->parseChunk($nextTpl, array('next' => $next)));
		}
		
		return $out;
	} else {
		$modx->sendErrorPage();
	}
} else {
	$modx->sendErrorPage();
}
```

Then call it in the dedicated page:
```
[!ImageView? 
&thumbSnippet=`sgThumb`
&thumbOptions=`400x300`
&tpl=`@CODE:
<div class="col-lg-3 col-md-4 col-xs-6 thumb">
	<a class="thumbnail" href="[+sg_image+]" target="_blank">
		<img class="img-responsive" src="[+thumb.sg_image+]" alt="[+dl.iteration+]. [+e.sg_title+]">
	</a>
</div>
`
&prevTpl=`@CODE:<a href="[~[*id*]~]?sgid=[+prev+]">prev</a>`
&nextTpl=`@CODE:<a href="[~[*id*]~]?sgid=[+next+]">next</a>`
!]
[+prev+] [+next+]
```

**Comment by leonie12** [comment]
Thank you. I will try it. The dedicated page is in MaxiGallery the same as the overview page.

Wouldn't it be possible to integrate this functionality (your snippet above) into SG? I think this would facilitate many MaxiGallery users the change to SG.

**Comment by Pathologic** [comment]
It's redundant and unclaimed feature. If image description requires  a separate page to display, then most of developers will prefer to use document tree and image tvs instead of a gallery.

**Comment by leonie12** [comment]
I do not think that it is desirable to have hundred(s of) pages in the site tree. For me it seems much easier to have them bundled in a gallery with ZIP-upload, dragsort etc. Especially if those are living under the categorie 'gallery this' and 'gallery that'.
In MaxiGallery there was/still is this mode available and I would be the first to claim to have it in SG ;-) .

What do you mean with 'It's redundant'? Is there another way of doing this with SG/DocLister that is unknown to me? 

With heavy use of google translator I found your script to transfer MG to SG in a russian speaking forum (I would like to be able to speak russian – there is so much going on related to Evo). How Do I use it? Install as a plugin?

**Comment by Pathologic** [comment]
By the way, I've created a lot of sites, both Evo and Revo, but never came across such gallery output, it's possible by default only in MaxiGallery. But you see, it can be built with not so complex snippet.

To use converter:
1. Install and configure SG, open the document with gallery attached to create db tables.
2. Create converter.php file near index.php and paste converter code there.
3. Run converter.php, better with server console to avoid execution time limits, but you may use a browser as well if you gallery is not very large. Be sure you'll have backup if something goes wrong (:
